name: E2E Regression

on:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master
  schedule:
      - cron: ''
  workflow_dispatch:

env:
    TARGET: "%regex[.*Test.*],com.automationexercices.tests.**.**,com.automationexercices.tests.**"

jobs:
   chrome_linux_Test:
     runs-on: ubuntu-latest
     permissions:
       checks: write
     steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'


      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.12

      - name: Running Tests
        continue-on-error: true
        run: mvn -Dtest="${TARGET}" -DexecutionType="LocalHeadless"  -DbrowserType="chrome" clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: chrome_linux_Report
          path: "test-output/reports/*.html"

   Edge_Windows_Test:
     runs-on: windows-latest
     permissions:
       checks: write
     steps:
       - name: checkout code
         uses: actions/checkout@v6

       - name: Setup Java
         uses: actions/setup-java@v5
         with:
           distribution: 'zulu' # See 'Supported distributions' for available options
           java-version: '17'


       - name: Setup Maven
         uses: stCarolas/setup-maven@v5
         with:
           maven-version: 3.9.12

       - name: Running Tests
         continue-on-error: true
         run: mvn -Dtest="${TARGET}" -DexecutionType="LocalHeadless"  -DbrowserType="Edge" clean test

       - name: Upload Test Results
         uses: actions/upload-artifact@v4
         with:
           name: Edge_Windows_Report
           path: "test-output/reports/*.html"